server:
  port: 0

spring:
  application:
    name: users
  config:
    import:
      - aws-secretsmanager:/secret/users/
      - aws-parameterstore:/config/users/
      - aws-parameterstore:/config/application/
  datasource:
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${jwt.issuer.uri}

eureka:
  client:
    service-url:
      defaultZone: ${eureka.default.zone}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}



