server:
  port: 8085

spring:
  application:
    name: users
  config:
    import:
      - aws-secretsmanager:/secret/users/
      - aws-parameterstore:/config/users/
      - aws-parameterstore:/config/application/
  datasource:
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.base-url}/realms/${keycloak.realm}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true

